### ISSUE TITLE
Pather.js getPresetUnits error

### ISSUE THREAD

**Issue by jmkim2ea** [theksk/autosmurf#2]
Hi..
It's great work..
I have a question.
I have got error message "Pather.js(1214)  getPresetUnits failed, couldn't access the level"..
I guess Sorc can't use teleport in act 1 first level but the script do ..so I got the error message I guess.
I test my autobuild file and Sorc file with other autosmurf file, it's fine but they have another error : -(
My English is not good..Sorry^^

**Comment by theksk** [comment]
do you have cubing=true in char config? that would make a lvl1 char go for a1 (which it cannot) to get the cube.

**Comment by jmkim2ea** [comment]
You are my godsend helper..Thanks you so much... :+1:
